### ISSUE TITLE
Not following markdown heading hierarchy breaks atom.xml

### ISSUE THREAD

**Issue by martinfleis** [mrocklin/mrocklin.github.io#7]
Hey, I've been reading this blog via RSS reader (reeder 5 to be precise) and noticed that when the markdown heading hierarchy is not followed, the heading is missing and a MyST error shows up instead.  So I see this:

```
System Message: WARNING/2 (/home/runner/work/mrocklin.github.io/mrocklin.github.io/redesign-blog.md, line 28)

Document headings start at H2, not H1 [myst.header]
```

instead of this heading https://github.com/mrocklin/mrocklin.github.io/blob/02a86ecebba7378946ee9bb2464a24fefb4fa59c/redesign-blog.md?plain=1#L28-L29

My assumption is that it comes from the mix of `###` headings and underlined headings in the same document and MyST struggles to properly decode those when rendering the atom output.

Checking the atom.xml, it actually shows up more than 100x in the feed.

**Comment by mrocklin** [comment]
Thank you for reporting @martinfleis .  I *hope* that https://github.com/mrocklin/mrocklin.github.io/commit/6a69772f870b2c3e8b7e433626e1a935652edb24 resolves this.  

Can you confirm?

**Comment by martinfleis** [comment]
Yes, that fixed it ;).

**Comment by mrocklin** [comment]
Excellent.  Thank you again for reporting this.  I imagine that you spent more time tracking down the issue than I spent fixing it 🙂
